# Generated by Django 3.1.3 on 2020-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instytution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=600)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'organizacja pozarządowa'), (3, 'domyślnie fundacja'), (2, 'zbiórka lokalna'), (0, 'fundacja')])),
                ('categories', models.ManyToManyField(to='myapp.Category')),
            ],
        ),
    ]
