# Generated by Django 3.1.3 on 2020-11-05 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'domyślnie fundacja'), (1, 'organizacja pozarządowa'), (0, 'fundacja'), (2, 'zbiórka lokalna')]),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=9)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('pick_up_date', models.DateTimeField(auto_now_add=True)),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(max_length=250)),
                ('categories', models.ManyToManyField(to='myapp.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instytution', to='myapp.instytution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
