# Generated by Django 3.1.3 on 2020-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'zbiórka lokalna'), (3, 'domyślnie fundacja'), (1, 'organizacja pozarządowa'), (0, 'fundacja')]),
        ),
    ]
