# Generated by Django 3.1.3 on 2020-11-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201105_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'domyślnie fundacja'), (1, 'organizacja pozarządowa'), (2, 'zbiórka lokalna'), (0, 'fundacja')]),
        ),
    ]
