# Generated by Django 3.1.3 on 2020-11-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201107_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'fundacja'), (2, 'zbiórka lokalna'), (3, 'domyślnie fundacja'), (1, 'organizacja pozarządowa')]),
        ),
    ]
