# Generated by Django 3.1.3 on 2020-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201108_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'zbiórka lokalna'), (0, 'fundacja'), (1, 'organizacja pozarządowa'), (3, 'domyślnie fundacja')]),
        ),
    ]
