# Generated by Django 3.1.3 on 2020-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201105_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'domyślnie fundacja'), (2, 'zbiórka lokalna'), (0, 'fundacja'), (1, 'organizacja pozarządowa')]),
        ),
    ]
