# Generated by Django 3.1.3 on 2020-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201105_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'zbiórka lokalna'), (1, 'organizacja pozarządowa'), (0, 'fundacja'), (3, 'domyślnie fundacja')]),
        ),
    ]
