# Generated by Django 3.1.3 on 2020-11-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201111_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'zbiórka lokalna'), (3, 'domyślnie fundacja'), (1, 'organizacja pozarządowa'), (0, 'fundacja')]),
        ),
    ]
