# Generated by Django 3.1.3 on 2020-11-18 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201111_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='don_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'zbiórka lokalna'), (1, 'organizacja pozarządowa'), (3, 'domyślnie fundacja'), (0, 'fundacja')]),
        ),
    ]
