# Generated by Django 3.1.3 on 2020-11-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201118_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instytution',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'zbiórka lokalna'), (0, 'fundacja'), (3, 'domyślnie fundacja'), (1, 'organizacja pozarządowa')]),
        ),
    ]
